### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by xiprox** [xiprox/Car-Hiring-System#18]
#### User
```
    int id;
    char username[20];
    char password[20];
    char name[20];
    char surname[20];
    int type; // One of TYPE_DEV, TYPE_ADMIN or TYPE_CUSTOMER (See user.h)
    struct Hire hiredCars[3];
```
- [x] Done

#### Car
```
    int id;
    int price;
    char model[20];
    char manufacturer[40];
    int kilometrage;
    int hired;
```
- [x] Done

#### Hire
```
    int id;
    int hireDate;
```
- [x] Done

#### Relationships
Cars are assigned to users by their IDs and marked as hired when hired. We don’t really need to tie cars to the users that hire them. 

#### Developer 
- [x] Done

#### Administrator
- [x] Done

#### Customer
- [x] Done

## Administrator Tasks
- [x] #2: Loading all cars from database 
- [x] #3: Adding a new car
- [x] #4: Removing a car
- [x] #5: Searching cars by given parameters
- [x] #6: Displaying cars by given parameters
- [x] #7: Updating car info
- [x] #8: Printing a car array on screen

## Customer Tasks
- [x] #9: Hiring a car
- [x] #10: Returning a hired car
- [x] #11: Searching and displaying hired cars
- [x] #12: Searching and displaying available cars
- [x] #14: Displaying all cars' info that are hired by the current customer

## Bonus stuff
- [x] #15: Price calculations
- [x] #16: Car classes
- [x] #17: Hire logs

------

### Report
- [x] Done

### Presentation
- [x] Done
